name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.SSHKEY_PASSPHRASE }}
          source: "."
          target: "/home/${{ secrets.USERNAME }}/correcteur-fuyukitrad"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}  
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          envs: LARGE_SECRET_PASSPHRASE
          passphrase: ${{ secrets.SSHKEY_PASSPHRASE }}
          script: cd /home/${{ secrets.USERNAME }}/correcteur-fuyukitrad && chmod +x ./decrypt.sh && ./decrypt.sh && docker-compose down && docker-compose up --build -d && sleep 5s && docker ps
