name: "Build Docker Workflow"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker
        run: docker-compose up --build -d && (if [ $(docker ps -q $1 | wc -l) -ne 4 ]; then exit 1 ;fi)